[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pycaver"
version = "0.0.1"
description = "A python wrapper for the channel calculation software caver."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
authors = [
    { name = "Jan-Niklas Forster" }
]

dependencies = [
    "auto_mix_prep==0.2.0",
    "matplotlib==3.11.1",
    "mypkg==1.0.0",
    "networkx==3.4.2",
    "pandas==3.0.5",
    "platformdirs==4.11.7",
    "plotly==6.0.0"
]

[project.scripts]
pycaver = "pycaver.cli:entry"


[tool.setuptools.packages.find]
where = ["."]
include = ["pycaver*"]

[tool.setuptools.package-data]
pycaver = ["utils/*.txt"]