import os
import pandas as pd

SINGLE_AA = {
    "GLY": "G",
    "ALA": "A",
    "VAL": "V",
    "LEU": "L",
    "ILE": "I",
    "THR": "T",
    "SER": "S",
    "MET": "M",
    "CYS": "C",
    "PRO": "P",
    "PHE": "F",
    "TYR": "Y",
    "TRP": "W",
    "HIS": "H",
    "LYS": "K",
    "ARG": "R",
    "ASP": "D",
    "GLU": "E",
    "ASN": "N",
    "GLN": "Q",
}

def parse_residue_line(line : str) -> dict:
    line_rep = {}
    parts = line.split(" ")
    parts = [x for x in parts if x != ""]
    line_rep["chain"] = parts[0]
    line_rep["residue"] = parts[1]
    line_rep["AA"] = parts[2]
    line_rep["N"] = parts[3]
    return line_rep

def parse_tunnel_residues(input_path : str) -> list:
    """
    Read the residues.txt file generated by caver
    """
    if not os.path.exists(input_path):
        print(f"Residues file {input_path} does not exist")
        return {}
    else:
        with open(input_path, "r") as f:
            lines = f.readlines()

        residue_data = []
        current_cluster = None
        for line in lines:
            # skip comments
            if line.startswith("#"):
                continue
            
            # new tunnel cluster
            if line.startswith("="):
                if current_cluster is None:
                    # create current cluster
                    current_cluster = pd.DataFrame(columns=["chain", "residue", "AA", "N"])
                    continue
                else:
                    # save current cluster to residue data and create new one
                    residue_data.append(current_cluster.to_dict())
                    current_cluster = pd.DataFrame(columns=["chain", "residue", "AA", "N"])
                    continue

            # normal row
            current_cluster = pd.concat([current_cluster, pd.DataFrame([parse_residue_line(line)])], ignore_index=True)

        return residue_data

def create_fingerprint(aa_list : list) -> tuple:
    """
    Fingerprint stuff
    [A, R, N, D, C, Q, E, G, H, I, L, K, M, F, P, S, T, W, Y, V] 
    -> [Alanine, Arginine, Asparagine, Aspartic Acid, Cysteine, Glutamine, Glutamic Acid, Glycine, Histidine, Isoleucine, Leucine, Lysine, Methionine, Phenylalanine, Proline, Serine, Threonine, Tryptophan, Tyrosine, Valine]
    """
    res = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

    for aa in aa_list:
        if aa == "A":
            res[0] += 1
        elif aa == "R":
            res[1] += 1
        elif aa == "N":
            res[2] += 1
        elif aa == "D":
            res[3] += 1
        elif aa == "C":
            res[4] += 1
        elif aa == "Q":
            res[5] += 1
        elif aa == "E":
            res[6] += 1
        elif aa == "G":
            res[7] += 1
        elif aa == "H":
            res[8] += 1
        elif aa == "I":
            res[9] += 1
        elif aa == "L":
            res[10] += 1
        elif aa == "K":
            res[11] += 1
        elif aa == "M":
            res[12] += 1
        elif aa == "F":
            res[13] += 1
        elif aa == "P":
            res[14] += 1
        elif aa == "S":
            res[15] += 1
        elif aa == "T":
            res[16] += 1
        elif aa == "W":
            res[17] += 1
        elif aa == "Y":
            res[18] += 1
        elif aa == "V":
            res[19] += 1

    return res


def parse_tunnel_residue_summary(input_path : str) -> dict:
    """
    - Shared Residues fingerprint -> most probably the ones gating
        read all residues into sets and build the union/define a cutoff of f.e. 80% to keep residues
    - summed fingerprint
    """
    # parse the tunnel residues
    tunnel_residue_list = parse_tunnel_residues(input_path)

    tunnel_residues_per_tunnel = []
    for tunnel in tunnel_residue_list:
        tunnel_residues = []

        for k in tunnel["chain"].keys():
            res = tunnel["chain"][k] +":"+ tunnel["residue"][k] +":"+ tunnel["AA"][k]
            tunnel_residues.append(res)

        tunnel_residues_per_tunnel.append(tunnel_residues)

    # create a list with all residues
    all_res = set()
    for i in tunnel_residues_per_tunnel:
        all_res.update(i)

    all_res = list(all_res)
    # -> all_res fingerprint

    # create a list with only the "important" residues: meaning the ones that are in > x % of the tunnels, and 100% of the tunnels up to 50% -> lets do 100, 75, 50
    aa_100 = []
    aa_75 = []
    aa_50 = []
    aa_all = []
    for res in all_res:
        exists_c = 0

        for res_per_tunnel in tunnel_residues_per_tunnel:
            if res in res_per_tunnel:
                exists_c += 1

        score = float(exists_c / len(tunnel_residues_per_tunnel))
        
        aa = res.split(":")[2]

        if aa in SINGLE_AA.keys():
            aa_all.append(SINGLE_AA[aa])

        if score == 1.0:
            if aa in SINGLE_AA.keys():
                aa_100.append(SINGLE_AA[aa])
        if score >= 0.75:
            if aa in SINGLE_AA.keys():
                aa_75.append(SINGLE_AA[aa])
        if score >= 0.5:
            if aa in SINGLE_AA.keys():
                aa_50.append(SINGLE_AA[aa])

    # create fingerprints
    res = {
        "aa_100_fingerprint": create_fingerprint(aa_100),
        "aa_75_fingerprint": create_fingerprint(aa_75),
        "aa_50_fingerprint": create_fingerprint(aa_50),
        "aa_all": create_fingerprint(aa_all)
    }

    return res
